# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RoboArena_config = debug
endif
ifeq ($(config),release)
  RoboArena_config = release
endif
ifeq ($(config),python)
  RoboArena_config = python
endif

PROJECTS := RoboArena

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RoboArena:
ifneq (,$(RoboArena_config))
	@echo "==== Building RoboArena ($(RoboArena_config)) ===="
	@${MAKE} --no-print-directory -C RoboArena -f Makefile config=$(RoboArena_config)
endif

clean:
	@${MAKE} --no-print-directory -C RoboArena -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  python"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RoboArena"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"